name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to the Heroku Container Registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

    - name: Build, push, and release to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:push web -a ${{ secrets.HEROKU_APP_NAME }}
        heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}

    - name: Ensure the app is running
      run: |
        sleep 20
        curl -sSfL https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com || exit 1
